language: python
sudo: false
branches:
  only:
  - master
  - "/^\\d\\.\\d+$/"
  - "/^\\d\\.\\d+\\.\\d+(rc\\d+|\\.dev\\d+)?$/"
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 2.7
    env: TOXENV=jessie
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
install:
- |
  if [ "$TOXENV" = "pypy" ]; then
    export PYENV_ROOT="$HOME/.pyenv"
    if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
      pushd "$PYENV_ROOT" && git pull && popd
    else
      rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
    fi
    # get latest portable PyPy from pyenv directly (thanks to natural version sort option -V)
    export PYPY_VERSION=`"$PYENV_ROOT/bin/pyenv" install --list |grep -o -E 'pypy-portable-[0-9][\.0-9]*$' |sort -V |tail -1`
    "$PYENV_ROOT/bin/pyenv" install --skip-existing "$PYPY_VERSION"
    virtualenv --python="$PYENV_ROOT/versions/$PYPY_VERSION/bin/python" "$HOME/virtualenvs/$PYPY_VERSION"
    source "$HOME/virtualenvs/$PYPY_VERSION/bin/activate"
  fi
- pip install -U tox twine wheel codecov
script: tox
after_success:
- codecov
notifications:
  irc:
    use_notice: true
    skip_join: true
    channels:
    - irc.freenode.org#scrapy
cache:
  directories:
  - "$HOME/.cache/pip"
deploy:
  provider: pypi
  user: xiaowangwindow
  password:
    secure: W5poPG0a/jx8Wt4xpguSJkOt3rdmOuiO8GylZeY7aqK4uSAfCw6CIrf1XrWBEgtz903m2TpobKgcuRE/+ZB5FNnT8+/ZrpUMPNPqMBl3UxfrHFyo/LOZHnex24ETjLsBuj21OAl+P7TKvFYUEKOr9htyN65OTIOHeN7JR3rdRgydrcVbwSuAnI0X5MEMrnphZQFAaaMExv4HcsT1j6f7/Q4un2StynZOZidcuNfIzLd4TWX16PE2w2EvR9SbK6I5IKxEdkmgQOEbwmx/I4kX55t+5Jjux3eLTUnY1QvJVWuZYx3pQThS+HBwP7SYznR+p45HF735e+SIHXNTuqXPwx0tHwflToO/RF9fLkQl/TpE8A1JHOF2+jILENum38EQGcSas8I/uMWOwNzpIVpeC4XlyqQU9Mo85VAwsL6sBoLw/y+UprxCoDJA1qv+GigxEEfO9prHLyxajJxRNXWHnJ8IEH6r48PwP885lZkC5NUwTMHbsy5Cml1BK+w0RWuYG0e6o9Rphq3NPWRCxfZ8xfKpaobD/zSbxZck1hspk1MRJ6XxgRPzhuQzJVvP9uXn/Q6MquJQsTN1i6Da17Gjo2gYcFn8EH98eaAzR1N5UrtePj2CMZiA3Lrpn+zDeV6+P+biVjNmt42JHFIV6Gg8AF8PHi8fpEuguxVkRVoo/Bk=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: xiaowangwindow/scrapy-rotated-proxy
